### PR TITLE
fix: broken grammar of LIKELIHOOD

### PR DESCRIPTION
**Pull request by bajinsheng**
To avoid the grammar error: `The second argument of LIKELIHOOD must be a float number within 0.0 -1.0`

### CODE REVIEW

**Comment by bajinsheng** [comment]
This fix works for SQLite >=3.6.0

**Review by mrigger — COMMENTED** [review]
I assume with this change, we can also remove the corresponding expected error below? https://github.com/sqlancer/sqlancer/blob/b5eb2153dfd06bf50aca0f98eb32383b389a933f/src/sqlancer/sqlite3/SQLite3Errors.java#L24

**Comment by bajinsheng** [comment]
Oh yes. Didn't notice that.

**Review by mrigger — APPROVED** [review]
LGTM!

**Pull request merged**
