### PR TITLE
[StoneDB] Remove implementation

### PR DESCRIPTION
**Pull request by malwaregarry**
Removing StoneDB from the codebase since the implementation is broken and StoneDB seems to be unmaintained at the moment.
This is part of efforts to improve SQLancer's architecture and codebase in general. If it is being used, we can revert the PR.

@ZhengLin-Li since you worked on this implementation. Do you know whether the StoneDB is still working on the database?

### CODE REVIEW

**Comment by ZhengLin-Li** [comment]
I'm unsure if StoneDB is still actively maintained. After joining their Slack community, I noticed there's been no activity or messages this year. Additionally, their commit history shows that updates haven't been made in quite some time.

**Comment by malwaregarry** [comment]
hmm ok, are you ok with us removing it for now? @ZhengLin-Li

**Comment by ZhengLin-Li** [comment]
> alright, are you ok with us removing it for now? @ZhengLin-Li

oh yeah, let's remove

**Comment by mrigger** [comment]
Sounds good, we can always re-add by reverting the PR in case development continues.

@malwaregarry, perhaps we could have a table in the `README.md` that lists implementations that were removed and the corresponding reason?

**Comment by malwaregarry** [comment]
ok sure, do you want the `README.md` in this PR or another?

**Comment by mrigger** [comment]
Hmm, a separate one would be okay. I guess we could then also reference the removed NoSQL databases (https://github.com/sqlancer/sqlancer/pull/915).

**Pull request merged**
