### PR TITLE
Remove PQS

### PR DESCRIPTION
**Pull request by malwaregarry**
Removed PQS test oracles as they are currently unmaintained and different from the other test oracles

Also removed TimeScaleDB as it was only making use of the PQS test oracle (might need to re-open #24)

### CODE REVIEW

**Comment by mrigger** [comment]
@def-, is PQS actively being used within Materialize? We are considering removing it from the codebase as part of efforts to improve SQLancer's architecture and codebase in general. If it's being used, we should not remove it (at least for Materialize).

**Comment by def-** [comment]
Yes, we use it in Materialize.

**Comment by malwaregarry** [comment]
ok sure, i can add back materialize

**Comment by mrigger** [comment]
Hmm, I wonder if we should perhaps just leave PQS in the source base. It might be that also other companies are still using it, and I guess we cannot simplify the architecture as soon as we have one implementation that uses PQS. What do you think, @malwaregarry?

**Comment by malwaregarry** [comment]
yup that makes sense. In that case,  instead of consolidating an oracle for PQS, we can move most of the logic into the generator and the oracle just executes and compares. How does this sound , @mrigger?

**Pull request closed without merging**
