### PR TITLE
[CnosDB] Add CI & tests

### PR DESCRIPTION
**Pull request by malwaregarry**
Added tests but current implementation results in errors. The database also crashes sporadically

### CODE REVIEW

**Comment by mrigger** [comment]
Does it still result in errors/crashes? I see the current CI check passes. In case the crashes can be prevented by setting the number of queries to 0, that might also be an option.

**Comment by malwaregarry** [comment]
let me investigate it some more tomorrow first before merging

**Comment by malwaregarry** [comment]
I couldn't figure out what is causing the queries to crash the database. Can we leave the number of queries to be at 0?

**Comment by malwaregarry** [comment]
> With the number of queries being set to 0, does the database system still crash?
No crashes with 0 queries.

I've added a comment in the test files

**Comment by mrigger** [comment]
Sounds good, then let's merge it. It seems after the added comment, the formatting test is failing now.

Should we also open an issue in CnosDB to point out that SQLancer still triggers crashes in their system?

**Comment by malwaregarry** [comment]
> Should we also open an issue in CnosDB to point out that SQLancer still triggers crashes in their system?

There are some similar issues open reporting crashes: https://github.com/cnosdb/cnosdb/issues/1801  https://github.com/cnosdb/cnosdb/issues/1445

**Pull request merged**
