### PR TITLE
[Clickhouse] Update expected errors and pin version to latest LTS

### PR DESCRIPTION
**Pull request by malwaregarry**
PR to fix checks for Clickhouse which has been failing due to an updated error message.

### CODE REVIEW

**Comment by mrigger** [comment]
@qoega, do you think it's okay to pin the version? We are struggling with many failing CI tests, and one way to address this is to pin the version to the latest supported release of each database system.

**Comment by qoega** [comment]
Do you see more ClickHouse failures? Pinning is ok, we test master by ourselves

**Comment by malwaregarry** [comment]
That was the only error I saw

**Comment by mrigger** [comment]
Merging this one. Btw, @qoega, it seems the just-merged PR triggered a potential issue (see https://github.com/sqlancer/sqlancer/actions/runs/8505272902/job/23293479849):

> Code: 10. DB::Exception: Not found column __table1.c0: in block __table2.c0 Int32 Int32(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.4.1.183 (official build))

**Review by mrigger — APPROVED** [review]

**Comment by mrigger** [comment]
@qoega, if you think of it, it would be great if you could update the ClickHouse version from time to time (e.g., if we forget to do so).

**Pull request merged**
