### PR TITLE
[MySQL] Add bugs 114533 and 114544

### PR DESCRIPTION
**Pull request by malwaregarry**
The checks for MySQL were detecting an error caused by Java parsing an invalid string. I fixed this by passing the exception up as an `SQLException` and adding a new `ExpectedError`

~~There is still a potential bug reported, which I will investigate after this PR is merged.~~
https://bugs.mysql.com/bug.php?id=114533
https://bugs.mysql.com/bug.php?id=114534

### CODE REVIEW

**Comment by mrigger** [comment]
This looks like a bug in the JDBC driver to me. I think it would be ideal to reduce this case, report it to MySQL (if we believe it's indeed a bug), and then add it as a known bug, rather than an expected error.

**Comment by malwaregarry** [comment]
```
DROP DATABASE IF EXISTS database3;
CREATE DATABASE database3;
USE database3;
CREATE TABLE IF NOT EXISTS t0(c0 FLOAT ZEROFILL);
INSERT INTO t0(c0) VALUES("-0");
SELECT t0.c0 FROM t0;  --0000000000-0
```

I reduced the error to this.  Seems to be  because of a column with ZEROFILL and a negative 0.

**Comment by malwaregarry** [comment]
@mrigger the known bugs have been added

**Review by mrigger — APPROVED** [review]

**Comment by mrigger** [comment]
It seems there is still another location where the JDBC issue is triggered: https://github.com/sqlancer/sqlancer/actions/runs/8505272902/job/23293481262.

**Pull request merged**
