### PR TITLE
feat: bypass logical XOR

### PR DESCRIPTION
**Pull request by ZhengLin-Li**
feat: bypass logical XOR 

It seams that the expected supported operator is not actually supported so let's bypass it.

image

### CODE REVIEW

**Comment by bajinsheng** [comment]
If it is a bug, we can bypass it in this way. If the XOR is not supported, we can directly remove the XOR.

**Review by bajinsheng — APPROVED** [review]

**Comment by bajinsheng** [comment]
@mrigger Zhenglin explained to me it is a bug because the document shows the XOR is supported, so I think we can merge this PR.

**Comment by mrigger** [comment]
Okay, sounds good. There is a failing Checkstyle check. After addressing it, we can merge the PR.

**Comment by ZhengLin-Li** [comment]
> Okay, sounds good. There is a failing Checkstyle check. After addressing it, we can merge the PR.

Done

**Pull request merged**
