### PR TITLE
Remove NoSQL databases

### PR DESCRIPTION
**Pull request by malwaregarry**
Removed NoSQL databases so that it is easier to consolidate code for the refactoring effort.

#### Databases removed:
* MongoDB
* ArangoDB
*  Cosmos

### CODE REVIEW

**Review by mrigger — APPROVED** [review]
LGTM, thanks! Just for documentation: these implementations are, to the best of my knowledge, not actively used and make it more difficult to maintain SQLancer and hinder the ongoing efforts to improve SQLancer's architecture.

**Comment by NayameoW** [comment]
Hi, thanks for your commit. I merged it into my working branch but encountered an issue. Here’s the exception that was thrown:
Exception in thread "main" java.util.ServiceConfigurationError: sqlancer.DatabaseProvider: Provider sqlancer.arangodb.ArangoDBProvider not found
Could you please help me with this? Thank you!

**Comment by mrigger** [comment]
Did you try `mvn clean`? If that doesn't work, something might have gone wrong with your merge.

**Comment by NayameoW** [comment]
> Did you try `mvn clean`? If that doesn't work, something might have gone wrong with your merge.

Thanks! Something went wrong with my IDEA, and this really helps.

**Pull request merged**
