### PR TITLE
tidb: not use DEFAULT if columns have not default value

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

before this PR
```
$ java -jar sqlancer-*.jar   --num-threads 8   --host "127.0.0.1" --port 4000 --username "root" --password ""   tidb
[2023/01/16 00:02:09] Executed 0 queries (0 queries/s; 0.00/s dbs, successful statements: 82%). Threads shut down: 0.
[2023/01/16 00:02:14] Executed 9980 queries (1997 queries/s; 1.60/s dbs, successful statements: 73%). Threads shut down: 0.
[2023/01/16 00:02:19] Executed 25513 queries (3105 queries/s; 0.00/s dbs, successful statements: 73%). Threads shut down: 0.
[2023/01/16 00:02:24] Executed 41383 queries (3176 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
[2023/01/16 00:02:29] Executed 58620 queries (3446 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
[2023/01/16 00:02:34] Executed 63916 queries (1055 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
[2023/01/16 00:02:39] Executed 65185 queries (253 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
[2023/01/16 00:02:44] Executed 66895 queries (344 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
[2023/01/16 00:02:49] Executed 73724 queries (1366 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
[2023/01/16 00:02:54] Executed 86496 queries (2555 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
[2023/01/16 00:02:59] Executed 89432 queries (586 queries/s; 0.00/s dbs, successful statements: 72%). Threads shut down: 0.
```

after this PR

```
$ java -jar sqlancer-*.jar   --num-threads 8   --host "127.0.0.1" --port 4000 --username "root" --password ""   tidb
[2023/01/16 00:03:59] Executed 191 queries (38 queries/s; 0.20/s dbs, successful statements: 82%). Threads shut down: 0.
[2023/01/16 00:04:04] Executed 7808 queries (1524 queries/s; 1.20/s dbs, successful statements: 80%). Threads shut down: 0.
[2023/01/16 00:04:09] Executed 24424 queries (3323 queries/s; 0.20/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:14] Executed 43005 queries (3716 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:19] Executed 60919 queries (3582 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:24] Executed 79127 queries (3643 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:29] Executed 87297 queries (1632 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:34] Executed 100428 queries (2628 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:39] Executed 116637 queries (3243 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:44] Executed 130593 queries (2778 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:49] Executed 133773 queries (638 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:54] Executed 148368 queries (2920 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:04:59] Executed 165463 queries (3416 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:05:04] Executed 177157 queries (2338 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:05:09] Executed 192578 queries (3084 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:05:14] Executed 206208 queries (2726 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:05:19] Executed 224911 queries (3742 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
[2023/01/16 00:05:24] Executed 243062 queries (3628 queries/s; 0.00/s dbs, successful statements: 79%). Threads shut down: 0.
```

### CODE REVIEW

**Comment by mrigger** [comment]
This currently results in an exception:

``` 
java.lang.NullPointerException
	at sqlancer.tidb.TiDBSchema.getTableColumns(TiDBSchema.java:353)
	at sqlancer.tidb.TiDBSchema.fromConnection(TiDBSchema.java:302)
```

**Comment by hawkingrei** [comment]
> This currently results in an exception:
> 
> ```
> java.lang.NullPointerException
> 	at sqlancer.tidb.TiDBSchema.getTableColumns(TiDBSchema.java:353)
> 	at sqlancer.tidb.TiDBSchema.fromConnection(TiDBSchema.java:302)
> ```
> 
> Update: Sorry, I overlooked the draft state.

It has been fixed. Waiting for CI to succeed.

**Comment by hawkingrei** [comment]
```
--java.lang.AssertionError: double(8,6)
```

It is a bug in which sqlancer can not identify the ·```DOUBLE(M,D)```.  I will fix it in the next PR.

**Comment by mrigger** [comment]
Thanks! There is also a new error related to casting dates:

```
Data truncation: Incorrect datetime value: '134296591'
```

**Comment by hawkingrei** [comment]
> Thanks! There is also a new error related to casting dates:
> 
> ```
> Data truncation: Incorrect datetime value: '134296591'
> ```

Yes, I am thinking about whether we have a better way to avoid it. adding a skip error is not a good way. 🤔

**Comment by mrigger** [comment]
I think it's fine. It's difficult in many situations to avoid such semantic errors, and even invalid values can sometimes expose bugs (e.g., internal errors).

**Pull request merged**
