### PR TITLE
Update SQLite3 tests

### PR DESCRIPTION
**Pull request by malwaregarry**
Originally, the test did not include query partitioning oracles as the default was NoREC.

Also, `--num-queries` was previously set to 0, and is now changed to what is specified in `TestConfig`

### CODE REVIEW

**Review by mrigger — APPROVED** [review]

**Comment by malwaregarry** [comment]
yup, i ran both the tests for the full 5min without any errors. The problem with checks not running should be because they only run when something in `src/` is updated and this PR only edits `test/`. Is there any way to trigger it manually? If not should I update the workflow file to include `test/`? @mrigger

**Comment by malwaregarry** [comment]
i ran the both tests for 5 minutes and didn't get any errors

**Comment by mrigger** [comment]
Could you check whether you can reproduce this issue on the latest development build of SQLite (i.e., building it yourself)? If so, this likely is a bug in SQLite.

**Comment by malwaregarry** [comment]
ok i figured out what is causing this errror. It's  not a bug in sqlite.

It's because the first test deleted the db file while the second test is still using it. This could be why all other tests run are separated into their own class

**Comment by mrigger** [comment]
I see. Thanks for investigating!

**Comment by malwaregarry** [comment]
@mrigger i think you closed this PR instead of merging it.

**Pull request merged**
