### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mrigger**

### CODE REVIEW

**Comment by mrigger** [comment]
@bajinsheng, @kokrui, or @qoega, could one of you please double-check the changes before we merge them?

**Comment by bajinsheng** [comment]
It is not based on the latest master branch?

**Comment by mrigger** [comment]
It was based on the latest master, but I merged another PR. Merging this change, assuming that you have no other improvement suggestions or feedback. Thanks!

**Review by kokrui — APPROVED** [review]
Yeah, LGTM!

**Pull request merged**
