### PR TITLE
tidb: support tidb_enable_non_prepared_plan_cache

### PR DESCRIPTION
**Pull request by hawkingrei**

### CODE REVIEW

**Comment by mrigger** [comment]
It seems the style check test is currently still failing?

**Comment by hawkingrei** [comment]
> It seems the style check test is currently still failing?

I find I must set nonPreparePlanCache true. But I want his default value to be false. Because it is an experiment function.

**Comment by mrigger** [comment]
I think the style check complains because you don't need to initialize the field to false - it is false without an explicit initialization.

**Comment by hawkingrei** [comment]
> I think the style check complains because you don't need to initialize the field to false - it is false without an explicit initialization.

I fixed it.

**Pull request merged**
