### PR TITLE
tidb: support cross join and on condition

### PR DESCRIPTION
**Pull request by bajinsheng**
Within: https://github.com/sqlancer/sqlancer/issues/822

### CODE REVIEW

**Comment by bajinsheng** [comment]
https://github.com/sqlancer/sqlancer/actions/runs/5291519663/jobs/9577179809?pr=827
QPG Tests (TiDB) seem triggering a bug in TiDB: runtime error: index out of boundary.

**Review by mrigger — APPROVED** [review]
LGTM. For the bug triggered by QPG, could we add it to the TiDBBugs class?

**Comment by bajinsheng** [comment]
Seems the tidb version is the docker version, it is a new bug? Maybe I report to tidb before adding it to tidbbug?

**Comment by mrigger** [comment]
Perhaps. Sounds good!

**Comment by bajinsheng** [comment]
https://github.com/pingcap/tidb/issues/44747

**Review by mrigger — APPROVED** [review]

**Comment by bajinsheng** [comment]
Still require your manual merge @mrigger.

**Pull request merged**
