### PR TITLE
PostgreSQL: Add regex error strings on encoding and infinity conversion

### PR DESCRIPTION
**Pull request by danolivo**
Just to avoid false errors.

### CODE REVIEW

**Review by mrigger — APPROVED** [review]
LGTM! Sorry for the delay - I was on vacation.

**Comment by mrigger** [comment]
It seems the CI fails due to a formatting error. Could you use `mvn formatter:format` to avoid this error?

**Comment by danolivo** [comment]
Ок, sorry for mistake - I'm totally newb in Java coding.

**Comment by mrigger** [comment]
No worries! You can execute `mvn verify -DskipTests=true` to see whether any check fails.

**Comment by mrigger** [comment]
Thanks a lot for the PR!

**Comment by danolivo** [comment]
It works now.
CI tests on Citus and Databend don't pass, but without artifacts it is difficult to find out an error.

**Comment by mrigger** [comment]
Great, thanks! The Citus and Databend failures are expected and not due to this PR.

**Pull request merged**
