### PR TITLE
Add an expected error class

### PR DESCRIPTION
**Pull request by mrigger**
This class should introduce additional flexibility when dealing with expected errors. For example, future improvements could add support for regular expressions.

Partly addresses https://github.com/sqlancer/sqlancer/issues/32.

### CODE REVIEW

**Comment by mrigger** [comment]
@nukoyluoglu or @qoega, do you want to have a quick look at this PR to see if the changes make sense to you, since they also affect your implementations?

**Comment by qoega** [comment]
My part looks OK.
Actually I haven't figured out yet if I can actually use regex for errors like `Something happened with TOKEN when TOKEN2`.

**Comment by mrigger** [comment]
Thanks for looking over the changes! Currently, this is not supported, but I plan to add such functionality in of the next PRs. It should then be possible to write an expected error specification like `"Something happened with .* when .*`"

**Comment by nukoyluoglu** [comment]
Looks good to me, thanks for applying the changes to the Citus classes as well!

**Pull request merged**
