### PR TITLE
feat: add support of 8.0 version

### PR DESCRIPTION
**Pull request by ZhengLin-Li**
feat: add support of 8.0 version

In this PR, we add a flag to let user select which version of StoneDB to test.

### CODE REVIEW

**Comment by bajinsheng** [comment]
1. CI fails.
2. Only adding a flag? No code generation needs to be changed?

**Comment by ZhengLin-Li** [comment]
1. Yes, the CI fials. not sure the reason. The error message is: `org.opentest4j.AssertionFailedError: --test-8.0-version ==> expected: <true> but was: <false>`. Why it's expected value is true?
2. Basiclly yes, from my previous testing result, because the generation syntax is the same, only expected error message need to be changed or added.

**Comment by bajinsheng** [comment]
1. You can search Google to look for a solution.
2. Really? If so, why initially you show us there are some differences between the two versions?

**Comment by bajinsheng** [comment]
I guess it should be some new features or grammar in version 8.0

**Comment by ZhengLin-Li** [comment]
> I guess it should be some new features or grammar in version 8.0

absolutely yes. I still remember there is a difference in `alter table` statement. I will add supported sytax.

**Comment by bajinsheng** [comment]
Ok. LGTM.

**Comment by bajinsheng** [comment]
@mrigger The PR works for me.

**Comment by mrigger** [comment]
Thanks for the ping. Overlooked that we can merge the PR.

**Pull request merged**
