### PR TITLE
[ClickHouse] Use common NoREC Oracle

### PR DESCRIPTION
**Pull request by malwaregarry**

### CODE REVIEW

**Comment by mrigger** [comment]
@qoega, can we merge this PR? @malwaregarry is currently working on reducing redundancy within SQLancer's test oracle implementations.

**Comment by mrigger** [comment]
@qoega, just checking again about this. Would it be fine to merge?

**Comment by qoega** [comment]
I started looking but was distracted by an incident. Will look soon.

**Review by qoega — APPROVED** [review]
I have read through it. I'm happy someone read this code and was able to change something. Hope it will work 😉

**Comment by mrigger** [comment]
Great, thanks and fingers crossed. 😄

@malwaregarry, could you please resolve the conflict so we can merge the PR?

**Comment by malwaregarry** [comment]
ok done, should be ready for merge

**Review by mrigger — APPROVED** [review]

**Pull request merged**
