### PR TITLE
fix: don't pass username or password to duckdb

### PR DESCRIPTION
**Pull request by Mause**
It's an inmemory database and does not support them

### CODE REVIEW

**Comment by mrigger** [comment]
Thanks a lot for the PR! We can either merge as is, or you could consider the following improvement suggestion: we could throw an exception if a username or password is passed before we establish the connection. In order to check this reliably, you could introduce two new methods `isDefaultPassword` and `isDefaultUsername` in the `MainOption` class that check the respective fields (e.g., https://github.com/sqlancer/sqlancer/blob/0d61b0d23b5d5711fbc0b07013e54b93586cfc86/src/sqlancer/MainOptions.java#L51) for their default values. Should we just merge this PR, or would you like to implement this suggestion?

**Comment by Mause** [comment]
@mrigger I had a go at implementing that, let me know if I've understood you correctly

**Comment by mrigger** [comment]
Thanks, that's an even more elegant solution than I had in mind. :) We can merge once the format checks pass (`mvn verify -DskipTests=True`).

**Comment by Mause** [comment]
Thanks for the fast turnaround!

**Comment by mrigger** [comment]
Likewise, thanks a lot!

**Pull request merged**
