### PR TITLE
fix: add databend expr errors

### PR DESCRIPTION
**Pull request by TCeason**
in databend:

```sql
databend> select version();
+------------------------------------------------------------------------------------+
| version()                                                                          |
+------------------------------------------------------------------------------------+
| 8.0.26-v0.8.43-nightly-54e8a15(rust-1.67.0-nightly-2022-11-10T08:54:29.530960742Z) |
+------------------------------------------------------------------------------------+
1 row in set (0.05 sec)

databend> select 1/0;
ERROR 1105 (HY000): result row write failed: Code: 1006, displayText = / by zero.

```

### CODE REVIEW

**Comment by TCeason** [comment]
cc @mrigger please review, thx.

**Review by mrigger — APPROVED** [review]
LGTM, thanks!

**Comment by TCeason** [comment]
> LGTM, thanks!

Sqlancer is a good tool. It’s an honor and a pleasure to be a contributor.

**Comment by mrigger** [comment]
Thanks a lot for your kind words and glad that you are a part of it!

**Pull request merged**
