### PR TITLE
Update Cockroach DB to v23.1.0-beta.2

### PR DESCRIPTION
**Pull request by rharding6373**
Update CockroachDB to v23.1.0-beta.2
    
Disable ignored errors from CockroachDB bugs that have been fixed.

### CODE REVIEW

**Comment by rharding6373** [comment]
I added some expected errors. I think I have all of the ones that were being hit early and consistently. This now runs successfully for me locally for several minutes without shutting down threads.

**Comment by mrigger** [comment]
Thanks for the PR, and sorry for the late review - I was ill the last couple of days. Currently, a style check is failing. Could you please execute `mvn formatter:format`?

**Comment by bajinsheng** [comment]
It is a bit weird that MariaDB and MySQL tests failed.

**Comment by mrigger** [comment]
They have been failing for a while now and are not even run - not sure why.

**Comment by rharding6373** [comment]
Thanks for the review! Fixed the formatting error, thanks for the instructions.

**Review by mrigger — APPROVED** [review]
LGTM, thanks again!

**Pull request merged**
