### PR TITLE
feat: add expected errors for stonedb 

### PR DESCRIPTION
**Pull request by ZhengLin-Li**
feat: add expected errors for stonedb

### CODE REVIEW

**Review by bajinsheng — APPROVED** [review]

**Review by SuriZhang — APPROVED** [review]
LGTM, but as a nitpick, please write your PR description and work on writing better commit messages. You can refer to https://github.com/sqlancer/sqlancer/blob/main/CONTRIBUTING.md#commit-history.
Also, squash your commits in this PR please.

**Comment by mrigger** [comment]
Seems there is a conflict now, so I cannot merge.

**Comment by ZhengLin-Li** [comment]
> Seems there is a conflict now, so I cannot merge.

have resolved the conflict.

**Comment by ZhengLin-Li** [comment]
When merging, we could use the squash and merge so that the commit history will be clear.

image

**Comment by mrigger** [comment]
@SuriZhang, we've actually recently given up on relying that the PR has a clean history. Now, we just squash every PR when merging.

**Pull request merged**
